### ISSUE TITLE
Dependend crate futures-io 0.3.1 does not compile

### ISSUE THREAD

**Issue by TimonTerBraak** [windelbouwman/lognplot#3]
I am not yet too familiar with rust to find out how to explicitly try an older version of futures-io. That would likely work as it seems to be an indirect dependency.
Or is my Rust to rusty..? I guess 1.39 is not too old yet...

**Comment by windelbouwman** [comment]
rust 1.39 should be recent enough. You might want to try to delete your Cargo.lock file and try to rebuild. Otherwise a cargo clean might help if you upgraded rust in the meantime.

Four your information, I'm using archlinux with rust 1.39.0

I'm unsure about the Cargo.lock file, should it be checked into git?

**Comment by TimonTerBraak** [comment]
I found a user-installed rusty cargo (0.21) of the early days (2017) when I tried rust on my system. It fell apart. A fresh cargo seems to be doing fine. Resolved!
